@echo off
setlocal

REM This file intentionally stays ASCII-only. PowerShell builds Korean paths.
chcp 65001 >nul

set "SERVER=root@211.45.162.155"
set "REMOTE_ROOT=/var/www/chamsosik"
set "REMOTE_TMP=/tmp/chamsosik_upload_no_exe_json"
set "STAGE_DIR=%TEMP%\chamsosik_upload_no_exe_json"
set "SSH_OPTS=-o BatchMode=yes -o ConnectTimeout=15"

echo [1/5] Prepare local staging folder without .exe, .json and .zip files...
powershell -NoProfile -ExecutionPolicy Bypass -EncodedCommand JABFAHIAcgBvAHIAQQBjAHQAaQBvAG4AUAByAGUAZgBlAHIAZQBuAGMAZQAgAD0AIAAnAFMAdABvAHAAJwAKACQAcgBvAG8AdAAgAD0AIAAoAEcAZQB0AC0ATABvAGMAYQB0AGkAbwBuACkALgBQAGEAdABoAAoAJABrAHIASQBuAHQAZQByAG4AZQB0ACAAPQAgAC0AagBvAGkAbgAgACgAWwBjAGgAYQByAFsAXQBdACgAMAB4AEQANQA1AEMALAAwAHgAQQBEADYARAAsADAAeABDADcANwA4ACwAMAB4AEQAMQAzADAALAAwAHgAQgAxADMANwAsADAAeAAwADAAMgBFACwAMAB4AEQANQA1AEMALAAwAHgAQQBEADYARAApACkACgAkAGMAaABhAG0AcwBvAHMAaQBrACAAPQAgAC0AagBvAGkAbgAgACgAWwBjAGgAYQByAFsAXQBdACgAMAB4AEMAQwAzADgALAAwAHgAQwAxADgAQwAsADAAeABDADIARABEACwAMAB4ADAAMAAyAEUALAAwAHgAMAAwADYAMwAsADAAeAAwADAANgBGACwAMAB4ADAAMAA2AEQAKQApAAoAJABsAG8AYwBhAGwAIAA9ACAASgBvAGkAbgAtAFAAYQB0AGgAIAAkAHIAbwBvAHQAIAAoAEoAbwBpAG4ALQBQAGEAdABoACAAJwB3AGUAYgBcAHAAdQBiAGwAaQBjACcAIAAoAEoAbwBpAG4ALQBQAGEAdABoACAAJABrAHIASQBuAHQAZQByAG4AZQB0ACAAJABjAGgAYQBtAHMAbwBzAGkAawApACkACgAkAHMAdABhAGcAZQAgAD0AIAAkAGUAbgB2ADoAUwBUAEEARwBFAF8ARABJAFIACgBpAGYAIAAoACEAKABUAGUAcwB0AC0AUABhAHQAaAAgAC0ATABpAHQAZQByAGEAbABQAGEAdABoACAAJABsAG8AYwBhAGwAKQApACAAewAKACAAIABXAHIAaQB0AGUALQBIAG8AcwB0ACAAIgBMAG8AYwBhAGwAIABmAG8AbABkAGUAcgAgAG4AbwB0ACAAZgBvAHUAbgBkADoAIAAkAGwAbwBjAGEAbAAiAAoAIAAgAGUAeABpAHQAIAAxAAoAfQAKAGkAZgAgACgAVABlAHMAdAAtAFAAYQB0AGgAIAAtAEwAaQB0AGUAcgBhAGwAUABhAHQAaAAgACQAcwB0AGEAZwBlACkAIAB7AAoAIAAgAFIAZQBtAG8AdgBlAC0ASQB0AGUAbQAgAC0ATABpAHQAZQByAGEAbABQAGEAdABoACAAJABzAHQAYQBnAGUAIAAtAFIAZQBjAHUAcgBzAGUAIAAtAEYAbwByAGMAZQAKAH0ACgBOAGUAdwAtAEkAdABlAG0AIAAtAEkAdABlAG0AVAB5AHAAZQAgAEQAaQByAGUAYwB0AG8AcgB5ACAALQBQAGEAdABoACAAJABzAHQAYQBnAGUAIAAtAEYAbwByAGMAZQAgAHwAIABPAHUAdAAtAE4AdQBsAGwACgAkAGEAcgBnAHMATABpAHMAdAAgAD0AIABAACgAJABsAG8AYwBhAGwALAAgACQAcwB0AGEAZwBlACwAIAAnAC8ARQAnACwAIAAnAC8AWABGACcALAAgACcAKgAuAGUAeABlACcALAAgACcAKgAuAGoAcwBvAG4AJwAsACAAJwAqAC4AegBpAHAAJwAsACAAJwAvAFgARAAnACwAIAAnAG4AbwBkAGUAXwBtAG8AZAB1AGwAZQBzACcALAAgACcALgBnAGkAdAAnACwAIAAnAC8AUgA6ADIAJwAsACAAJwAvAFcAOgAyACcAKQAKACYAIAByAG8AYgBvAGMAbwBwAHkALgBlAHgAZQAgAEAAYQByAGcAcwBMAGkAcwB0AAoAaQBmACAAKAAkAEwAQQBTAFQARQBYAEkAVABDAE8ARABFACAALQBnAGUAIAA4ACkAIAB7ACAAZQB4AGkAdAAgADEAIAB9AAoAZQB4AGkAdAAgADAA
if errorlevel 1 (
  echo Local staging failed.
  exit /b 1
)

echo [2/5] Ensure remote temporary folder exists...
ssh %SSH_OPTS% %SERVER% "rm -rf %REMOTE_TMP% && mkdir -p %REMOTE_TMP%"
if errorlevel 1 (
  echo Remote temporary folder setup failed.
  exit /b 1
)

echo [3/5] Upload staged files to %REMOTE_TMP% ...
scp %SSH_OPTS% -r "%STAGE_DIR%\*" %SERVER%:%REMOTE_TMP%/
if errorlevel 1 (
  echo Upload failed.
  exit /b 1
)

echo [4/5] Move files to final location with sudo...
ssh %SSH_OPTS% %SERVER% "sudo mkdir -p %REMOTE_ROOT% && sudo rsync -a %REMOTE_TMP%/ %REMOTE_ROOT%/ && rm -rf %REMOTE_TMP%"
if errorlevel 1 (
  echo Remote sync failed.
  exit /b 1
)

echo [5/5] Clean local staging folder...
rmdir /s /q "%STAGE_DIR%"

echo Done. Uploaded without .exe and .json files.
endlocal
