graph TD
A[ TOP 100] --> B(G국제 정세 불확실성 증대);
A --> C(코스피 급등 및 한국 야구 대표팀 8강 진출);
A --> D(드라마 ‘옥을 찾아서’);
A --> E(츤데레 남성의 소개팅 태도);
A --> F(고기 거래와 군량미 징수);
A --> G(고기를 차지하기 위한 경쟁);
A --> H(사랑하는 사람에게 엽서를 쓰는 영상);
A --> I(주술회전 시청자);
A --> J(스톤에이지 펫 제작 및 성장);
A --> K(리니지 클래식 25 버전 추타 구간 분석);
A --> L(스톤에이지 상점 구매와 펫 성장);
A --> M(붉은사막 게임 기대감 상승);
A --> N(국방부 주한미군 무기 반출 발언);
A --> O(대통령의 사드 시스템 전력 반출);
A --> P(이란과 미국 간의 중동 전쟁 예상 마무리);
A --> Q(이재명 대통령의 주한미군 전략 중동 이전 반대);
B --> Q;
C --> Q;
D --> Q;
E --> Q;
F --> Q;
G --> Q;
H --> Q;
I --> Q;
J --> Q;
K --> Q;
L --> Q;
M --> Q;
N --> Q;
O --> Q;
P --> Q;
Q --> R[#1];
Q --> S[#2];
Q --> T[#3];
Q --> U[#4];
Q --> V[#5];
Q --> W[#6];
Q --> X[#7];
Q --> Y[#8];
Q --> Z[#9];
Q --> AA[#10];
Q --> BB[#11];
Q --> CC[#12];
R[#1] --> AA;
S[#2] --> AA;
T[#3] --> AA;
U[#4] --> AA;
V[#5] --> AA;
W[#6] --> AA;
X[#7] --> AA;
Y[#8] --> AA;
Z[#9] --> AA;
AA --> BB;
BB --> CC;